language: android
jdk: oraclejdk8

branches:
  only:
    - master

android:
  components:
    - platform-tools
    - tools
    - build-tools-30.0.2
    - android-30
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support

script:
  - ./gradlew :library:build